### ISSUE TITLE
./gen_make.sh ?

### ISSUE THREAD

**Issue by enzo-watt** [wangell/pleroma#1]
Saw this in the installation section of the guide - but nowhere to be found in the Pleroma folder?

**Comment by wangell** [comment]
@enzo-watt 

The project is currently in heavy flux while I'm porting everything to Rust and is basically useless right now, on top of the old documentation being completely defunct.  You should be able to run the hosted version by running `make run-hosted` after cloning, but I haven't tested running it on a clean install in awhile.  Likewise, you can run the native version under QEMU with `make run-native`.  But version neither will do anything at this point.  I would check back in 1 - 2 months and I should have a working/useful demo up and running.

**Comment by coucher-du-soleil** [comment]
Let me know if I can help with anything - you've done a great job so far with documentation and all so I don't imagine having a significant role until my Rust skills are up to par (which shouldn't be long at this rate... hopefully). Once there's more to work with I could help with an actual site/domain/forum/etc?
